/*
 * This file is generated by jOOQ.
 */
package vlm.schema.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import vlm.schema.tables.Pledges;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PledgesRecord extends UpdatableRecordImpl<PledgesRecord> implements Record10<Long, Long, Long, Long, Long, Long, Long, Long, Integer, Boolean> {

    private static final long serialVersionUID = 1997481747;

    /**
     * Create a detached PledgesRecord
     */
    public PledgesRecord() {
        super(Pledges.PLEDGES);
    }

    /**
     * Create a detached, initialised PledgesRecord
     */
    public PledgesRecord(Long dbId, Long id, Long accountId, Long recipId, Long pledgeTotal, Long pledgeLatestTime, Long unpledgeTotal, Long withdrawTime, Integer height, Boolean latest) {
        super(Pledges.PLEDGES);

        set(0, dbId);
        set(1, id);
        set(2, accountId);
        set(3, recipId);
        set(4, pledgeTotal);
        set(5, pledgeLatestTime);
        set(6, unpledgeTotal);
        set(7, withdrawTime);
        set(8, height);
        set(9, latest);
    }

    /**
     * Getter for <code>DB.pledges.db_id</code>.
     */
    public Long getDbId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB.pledges.db_id</code>.
     */
    public void setDbId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB.pledges.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DB.pledges.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB.pledges.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>DB.pledges.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB.pledges.recip_id</code>.
     */
    public Long getRecipId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>DB.pledges.recip_id</code>.
     */
    public void setRecipId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB.pledges.pledge_total</code>.
     */
    public Long getPledgeTotal() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>DB.pledges.pledge_total</code>.
     */
    public void setPledgeTotal(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB.pledges.pledge_latest_time</code>.
     */
    public Long getPledgeLatestTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>DB.pledges.pledge_latest_time</code>.
     */
    public void setPledgeLatestTime(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB.pledges.unpledge_total</code>.
     */
    public Long getUnpledgeTotal() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>DB.pledges.unpledge_total</code>.
     */
    public void setUnpledgeTotal(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>DB.pledges.withdraw_time</code>.
     */
    public Long getWithdrawTime() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>DB.pledges.withdraw_time</code>.
     */
    public void setWithdrawTime(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>DB.pledges.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>DB.pledges.height</code>.
     */
    public void setHeight(Integer value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>DB.pledges.latest</code>.
     */
    public Boolean getLatest() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>DB.pledges.latest</code>.
     */
    public void setLatest(Boolean value) {
        set(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, Long, Long, Long, Long, Long, Integer, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, Long, Long, Long, Long, Long, Integer, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Pledges.PLEDGES.DB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Pledges.PLEDGES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Pledges.PLEDGES.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Pledges.PLEDGES.RECIP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Pledges.PLEDGES.PLEDGE_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Pledges.PLEDGES.PLEDGE_LATEST_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Pledges.PLEDGES.UNPLEDGE_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Pledges.PLEDGES.WITHDRAW_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Pledges.PLEDGES.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Pledges.PLEDGES.LATEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getRecipId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getPledgeTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getPledgeLatestTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getUnpledgeTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getWithdrawTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getLatest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getRecipId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getPledgeTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getPledgeLatestTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUnpledgeTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getWithdrawTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getLatest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value1(Long value) {
        setDbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value2(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value3(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value4(Long value) {
        setRecipId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value5(Long value) {
        setPledgeTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value6(Long value) {
        setPledgeLatestTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value7(Long value) {
        setUnpledgeTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value8(Long value) {
        setWithdrawTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value9(Integer value) {
        setHeight(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord value10(Boolean value) {
        setLatest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PledgesRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6, Long value7, Long value8, Integer value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
