/*
 * This file is generated by jOOQ.
 */
package vlm.schema.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import vlm.schema.Db;
import vlm.schema.Indexes;
import vlm.schema.Keys;
import vlm.schema.tables.records.PeerRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Peer extends TableImpl<PeerRecord> {

    /**
     * The reference instance of <code>DB.peer</code>
     */
    public static final Peer PEER = new Peer();
    private static final long serialVersionUID = -1223792823;
    /**
     * The column <code>DB.peer.address</code>.
     */
    public final TableField<PeerRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>DB.peer</code> table reference
     */
    public Peer() {
        this(DSL.name("peer"), null);
    }

    /**
     * Create an aliased <code>DB.peer</code> table reference
     */
    public Peer(String alias) {
        this(DSL.name(alias), PEER);
    }

    /**
     * Create an aliased <code>DB.peer</code> table reference
     */
    public Peer(Name alias) {
        this(alias, PEER);
    }

    private Peer(Name alias, Table<PeerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Peer(Name alias, Table<PeerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PeerRecord> getRecordType() {
        return PeerRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Db.DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PEER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PeerRecord> getPrimaryKey() {
        return Keys.KEY_PEER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PeerRecord>> getKeys() {
        return Arrays.<UniqueKey<PeerRecord>>asList(Keys.KEY_PEER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Peer as(String alias) {
        return new Peer(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Peer as(Name alias) {
        return new Peer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Peer rename(String name) {
        return new Peer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Peer rename(Name name) {
        return new Peer(name, null);
    }
}
